-- BizConnect KBank ODD Registration Table
-- Migration: 20250713-01_CreateKbankOddRegistration.sql
-- Description: Creates the KbankOddRegistration table for Online Direct Debit registration tracking

-- Create KbankOddRegistration table with PascalCase column names to match EF Core conventions
CREATE TABLE IF NOT EXISTS "KbankOddRegistration" (
    "Id" SERIAL PRIMARY KEY,
    "ExternalReference" VARCHAR(40) UNIQUE NOT NULL,
    "RegId" VARCHAR(40) NOT NULL,
    "EspaId" VARCHAR(40),
    "Status" VARCHAR(20) NOT NULL DEFAULT 'Pending',
    "ReturnCode" VARCHAR(10),
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ
);

-- Create unique index on ExternalReference for fast lookups
CREATE UNIQUE INDEX IF NOT EXISTS "IX_KbankOddRegistration_ExternalReference" 
ON "KbankOddRegistration" ("ExternalReference");

-- Create index on RegId for KBank callback lookups
CREATE INDEX IF NOT EXISTS "IX_KbankOddRegistration_RegId" 
ON "KbankOddRegistration" ("RegId");

-- Create index on Status for filtering by registration status
CREATE INDEX IF NOT EXISTS "IX_KbankOddRegistration_Status" 
ON "KbankOddRegistration" ("Status");

-- Create index on CreatedAt for chronological queries
CREATE INDEX IF NOT EXISTS "IX_KbankOddRegistration_CreatedAt" 
ON "KbankOddRegistration" ("CreatedAt");

-- Add comments for documentation
COMMENT ON TABLE "KbankOddRegistration" IS 'Tracks KBank Online Direct Debit registration requests and their status';
COMMENT ON COLUMN "KbankOddRegistration"."ExternalReference" IS 'Unique external reference generated by BizConnect (format: BIZyyyyMMddHHmmssfff)';
COMMENT ON COLUMN "KbankOddRegistration"."RegId" IS 'Registration ID returned by KBank after initialization';
COMMENT ON COLUMN "KbankOddRegistration"."EspaId" IS 'ESPA ID returned by KBank after successful registration';
COMMENT ON COLUMN "KbankOddRegistration"."Status" IS 'Registration status: Pending, Success, or Fail';
COMMENT ON COLUMN "KbankOddRegistration"."ReturnCode" IS 'Return code from KBank status update';

-- Record this migration in the schema version table
INSERT INTO "_SchemaVersion" ("Filename")
VALUES ('20250713-01_CreateKbankOddRegistration.sql')
ON CONFLICT ("Filename") DO NOTHING;
