using System;
using System.Collections.Generic;
using BizConnect.Dal.Models;
using Microsoft.EntityFrameworkCore;

namespace BizConnect.Dal;

public partial class BizConnectContext : DbContext
{
    public BizConnectContext(DbContextOptions<BizConnectContext> options)
        : base(options)
    {
    }

    public virtual DbSet<KbankOddRegistration> KbankOddRegistrations { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<_SchemaVersion> _SchemaVersions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasPostgresExtension("uuid-ossp");

        modelBuilder.Entity<KbankOddRegistration>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("KbankOddRegistration_pkey");

            entity.ToTable("KbankOddRegistration", tb => tb.HasComment("Tracks KBank Online Direct Debit registration requests and their status"));

            entity.HasIndex(e => e.CreatedAt, "IX_KbankOddRegistration_CreatedAt");

            entity.HasIndex(e => e.ExternalReference, "IX_KbankOddRegistration_ExternalReference").IsUnique();

            entity.HasIndex(e => e.RegId, "IX_KbankOddRegistration_RegId");

            entity.HasIndex(e => e.Status, "IX_KbankOddRegistration_Status");

            entity.HasIndex(e => e.ExternalReference, "KbankOddRegistration_ExternalReference_key").IsUnique();

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("now()");
            entity.Property(e => e.Email)
                .HasMaxLength(256)
                .HasComment("User email address for ODD registration");
            entity.Property(e => e.EspaId)
                .HasMaxLength(40)
                .HasComment("ESPA ID returned by KBank after successful registration");
            entity.Property(e => e.ExternalReference)
                .HasMaxLength(40)
                .HasComment("Unique external reference generated by BizConnect (format: BIZyyyyMMddHHmmssfff)");
            entity.Property(e => e.IdType)
                .HasMaxLength(30)
                .HasComment("ID type: National ID, Passport, Tax ID, or Company Tax ID");
            entity.Property(e => e.IdValue)
                .HasMaxLength(30)
                .HasComment("ID number/value corresponding to the selected ID type");
            entity.Property(e => e.MobileNo)
                .HasMaxLength(20)
                .HasComment("User mobile number (format: 08xxxxxxxx or +66xxxxxxxx)");
            entity.Property(e => e.RegId)
                .HasMaxLength(40)
                .HasComment("Registration ID returned by KBank after initialization");
            entity.Property(e => e.ReturnCode)
                .HasMaxLength(10)
                .HasComment("Return code from KBank status update");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValueSql("'Pending'::character varying")
                .HasComment("Registration status: Pending, Success, or Fail");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Users_pkey");

            entity.ToTable(tb => tb.HasComment("Application users with authentication and authorization data"));

            entity.HasIndex(e => e.IsActive, "IX_Users_IsActive");

            entity.HasIndex(e => e.Role, "IX_Users_Role");

            entity.HasIndex(e => e.Username, "IX_Users_Username").IsUnique();

            entity.Property(e => e.Id).HasComment("Primary key, auto-incrementing user identifier");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasComment("Timestamp when user was created");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasComment("Whether the user account is active and can log in");
            entity.Property(e => e.PasswordHash)
                .HasMaxLength(255)
                .HasComment("BCrypt hashed password");
            entity.Property(e => e.Role)
                .HasMaxLength(50)
                .HasComment("User role: Admin or User");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasComment("Timestamp when user was last updated (auto-updated by trigger)");
            entity.Property(e => e.Username)
                .HasMaxLength(100)
                .HasComment("Unique username for authentication");
        });

        modelBuilder.Entity<_SchemaVersion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("_SchemaVersion_pkey");

            entity.ToTable("_SchemaVersion", tb => tb.HasComment("Tracks applied database migration files"));

            entity.HasIndex(e => e.Filename, "IX_SchemaVersion_Filename").IsUnique();

            entity.HasIndex(e => e.Filename, "_SchemaVersion_Filename_key").IsUnique();

            entity.Property(e => e.AppliedAt)
                .HasDefaultValueSql("now()")
                .HasComment("Timestamp when the migration was applied");
            entity.Property(e => e.Filename)
                .HasMaxLength(255)
                .HasComment("Name of the migration file that was applied");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
