using System;
using System.Collections.Generic;

namespace BizConnect.Dal.Models;

/// <summary>
/// Tracks KBank Online Direct Debit registration requests and their status
/// </summary>
public partial class KbankOddRegistration
{
    public int Id { get; set; }

    /// <summary>
    /// Unique external reference generated by BizConnect (format: BIZyyyyMMddHHmmssfff)
    /// </summary>
    public string ExternalReference { get; set; } = null!;

    /// <summary>
    /// Registration ID returned by KBank after initialization
    /// </summary>
    public string RegId { get; set; } = null!;

    /// <summary>
    /// ESPA ID returned by KBank after successful registration
    /// </summary>
    public string? EspaId { get; set; }

    /// <summary>
    /// Registration status: Pending, Success, or Fail
    /// </summary>
    public string Status { get; set; } = null!;

    /// <summary>
    /// Return code from KBank status update
    /// </summary>
    public string? ReturnCode { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// User email address for ODD registration
    /// </summary>
    public string? Email { get; set; }

    /// <summary>
    /// User mobile number (format: 08xxxxxxxx or +66xxxxxxxx)
    /// </summary>
    public string? MobileNo { get; set; }

    /// <summary>
    /// ID type: National ID, Passport, Tax ID, or Company Tax ID
    /// </summary>
    public string? IdType { get; set; }

    /// <summary>
    /// ID number/value corresponding to the selected ID type
    /// </summary>
    public string? IdValue { get; set; }
}
