using System;
using System.Collections.Generic;

namespace BizConnect.Dal.Models;

/// <summary>
/// Consolidated table tracking KBank Online Direct Debit registration requests with integrated OTAC functionality
/// </summary>
public partial class KbankOddRegistration
{
    public int Id { get; set; }

    /// <summary>
    /// Unique external reference generated by BizConnect (format: BIZyyyyMMddHHmmssfff)
    /// </summary>
    public string ExternalReference { get; set; } = null!;

    /// <summary>
    /// Registration ID returned by KBank after initialization
    /// </summary>
    public string? RegId { get; set; }

    /// <summary>
    /// ESPA ID returned by KBank after successful registration
    /// </summary>
    public string? EspaId { get; set; }

    /// <summary>
    /// Registration status: NULL (unprocessed), Pending, Success, or Fail - set by KBank integration
    /// </summary>
    public string? Status { get; set; }

    /// <summary>
    /// Return code from KBank status update
    /// </summary>
    public string? ReturnCode { get; set; }

    /// <summary>
    /// Type of identification: National ID, Passport, Tax ID, or Company Tax ID
    /// </summary>
    public string? IdType { get; set; }

    /// <summary>
    /// Identification document number/value corresponding to the selected ID type
    /// </summary>
    public string? IdValue { get; set; }

    /// <summary>
    /// Customer full name for registration
    /// </summary>
    public string? FullName { get; set; }

    /// <summary>
    /// Customer mobile number in format 08xxxxxxxx or +66xxxxxxxx
    /// </summary>
    public string? MobileNo { get; set; }

    /// <summary>
    /// Bank account number for the ODD registration (10-15 digits)
    /// </summary>
    public string? AccountNo { get; set; }

    /// <summary>
    /// Foreign key reference to Branch table
    /// </summary>
    public int? BranchId { get; set; }

    /// <summary>
    /// The actual OTAC code (8-character alphanumeric)
    /// </summary>
    public string OtacCode { get; set; } = null!;

    /// <summary>
    /// OTAC state: Generated → Validated → Used
    /// </summary>
    public string OtacState { get; set; } = null!;

    /// <summary>
    /// User ID who generated this OTAC code
    /// </summary>
    public int GeneratedByUserId { get; set; }

    /// <summary>
    /// Number of OTAC validation attempts made
    /// </summary>
    public int AttemptCount { get; set; }

    /// <summary>
    /// TRUE if OTAC is locked due to too many failed attempts
    /// </summary>
    public bool IsLocked { get; set; }

    /// <summary>
    /// Timestamp of last OTAC validation attempt
    /// </summary>
    public DateTime? LastAttemptAt { get; set; }

    /// <summary>
    /// IP address of last OTAC validation attempt
    /// </summary>
    public string? LastAttemptIp { get; set; }

    /// <summary>
    /// When the OTAC code expires (typically 30 minutes from creation)
    /// </summary>
    public DateTime? OtacExpiresAt { get; set; }

    /// <summary>
    /// Timestamp when record was created
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Timestamp when record was last updated (auto-updated by trigger)
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// Status message in Thai language for UI display
    /// </summary>
    public string? StatusMessageTh { get; set; }

    /// <summary>
    /// Status message in English language for UI display
    /// </summary>
    public string? StatusMessageEn { get; set; }

    /// <summary>
    /// Error message in Thai language for UI display
    /// </summary>
    public string? ErrorMessageTh { get; set; }

    /// <summary>
    /// Error message in English language for UI display
    /// </summary>
    public string? ErrorMessageEn { get; set; }

    /// <summary>
    /// National identification number (separate from IdValue for clarity)
    /// </summary>
    public string? NationalId { get; set; }

    /// <summary>
    /// Mobile phone number in international format (alternative to MobileNo)
    /// </summary>
    public string? MobileNumber { get; set; }

    public virtual Branch? Branch { get; set; }

    public virtual User GeneratedByUser { get; set; } = null!;
}
