using System.ComponentModel.DataAnnotations;
using BizConnect.Dal.Models;
using BizConnect.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BizConnect.Areas.Admin.Controllers;

/// <summary>
/// Controller for managing One-Time Access Codes (OTAC) integrated with ODD registrations
/// Accessible by Admin and Employee roles only
/// </summary>
[Area("Admin")]
[Authorize(Policy = "AdminOrEmployee")]
public class OtacController : Controller
{
    private readonly IOddRegistrationService _oddRegistrationService;
    private readonly ILogger<OtacController> _logger;

    public OtacController(IOddRegistrationService oddRegistrationService, ILogger<OtacController> logger)
    {
        _oddRegistrationService = oddRegistrationService;
        _logger = logger;
    }

    /// <summary>
    /// Display list of OTAC registrations
    /// </summary>
    public async Task<IActionResult> Index()
    {
        var result = await _oddRegistrationService.GetRegistrationsAsync(page: 1, pageSize: 50);
        return View(result.Registrations);
    }

    /// <summary>
    /// Generate a new OTAC code
    /// </summary>
    [HttpGet]
    public IActionResult Generate()
    {
        return View(new GenerateOtacViewModel());
    }

    /// <summary>
    /// Process OTAC code generation
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Generate(GenerateOtacViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        try
        {
            var userId = int.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value ?? "0");
            
            // Generate OTAC using new service
            var otacCode = await _oddRegistrationService.GenerateOtacAsync(userId);
            var registration = await _oddRegistrationService.GetRegistrationByOtacAsync(otacCode);

            _logger.LogInformation("OTAC code {Code} generated by user {UserId} for registration {RegistrationId}", 
                otacCode, userId, registration?.Id);

            TempData["SuccessMessage"] = $"OTAC code generated successfully: {otacCode}";
            TempData["GeneratedCode"] = otacCode;
            TempData["RegistrationId"] = registration?.Id;
            TempData["ExpiresAt"] = registration?.OtacExpiresAt?.ToString("yyyy-MM-dd HH:mm:ss UTC");

            return RedirectToAction(nameof(Index));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating OTAC code for purpose {Purpose}", model.Purpose);
            ModelState.AddModelError(string.Empty, "An error occurred while generating the OTAC code. Please try again.");
            return View(model);
        }
    }

    /// <summary>
    /// Validate an OTAC code
    /// </summary>
    [HttpGet]
    public IActionResult Validate()
    {
        return View(new ValidateOtacViewModel());
    }

    /// <summary>
    /// Process OTAC code validation
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Validate(ValidateOtacViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        try
        {
            var clientIp = HttpContext.Connection.RemoteIpAddress?.ToString() ?? "Unknown";
            var (isValid, errorMessage) = await _oddRegistrationService.ValidateOtacAsync(model.Code, clientIp);

            if (isValid)
            {
                _logger.LogInformation("OTAC code {Code} validated successfully from IP {IP}", 
                    model.Code, clientIp);

                // Add OTAC verified claim to current session
                HttpContext.Session.SetString("otac_verified", "true");
                HttpContext.Session.SetString("otac_code", model.Code);
                HttpContext.Session.SetString("otac_verified_at", DateTime.UtcNow.ToString());

                TempData["SuccessMessage"] = "OTAC code validated successfully. You now have access to protected resources.";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                _logger.LogWarning("OTAC code validation failed for code {Code} from IP {IP}: {ErrorMessage}", 
                    model.Code, clientIp, errorMessage);
                ModelState.AddModelError(string.Empty, errorMessage);
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error validating OTAC code {Code}", model.Code);
            ModelState.AddModelError(string.Empty, "An error occurred while validating the OTAC code. Please try again.");
        }

        return View(model);
    }

    /// <summary>
    /// View OTAC registrations generated by current user
    /// </summary>
    public async Task<IActionResult> MyOtacCodes()
    {
        var userId = int.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value ?? "0");
        var result = await _oddRegistrationService.GetRegistrationsAsync(page: 1, pageSize: 100);
        
        // Filter by current user (this could be optimized with a search parameter in the service)
        var userRegistrations = result.Registrations.Where(r => r.GeneratedByUserId == userId);
        return View(userRegistrations);
    }

    /// <summary>
    /// Manual purge of expired OTAC codes (Admin only)
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Policy = "AdminOnly")]
    public async Task<IActionResult> PurgeExpired()
    {
        try
        {
            var purgedCount = await _oddRegistrationService.PurgeExpiredOtacCodesAsync();
            TempData["SuccessMessage"] = $"Successfully purged {purgedCount} expired OTAC registrations.";
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error purging expired OTAC registrations");
            TempData["ErrorMessage"] = "An error occurred while purging expired registrations.";
        }

        return RedirectToAction(nameof(Index));
    }

    /// <summary>
    /// Generate OTAC modal for specific registration
    /// </summary>
    [HttpGet]
    public IActionResult GenerateModal(int? registrationId = null)
    {
        var model = new GenerateOtacViewModel();
        
        if (registrationId.HasValue)
        {
            model.Purpose = $"ODD Registration #{registrationId}";
            model.RegistrationId = registrationId.Value;
        }
        
        return PartialView("_GenerateModal", model);
    }

    /// <summary>
    /// Process OTAC generation via AJAX
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> GenerateAjax(GenerateOtacViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return Json(new { 
                success = false, 
                message = "Please check your input and try again.",
                errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList()
            });
        }

        try
        {
            var userId = int.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value ?? "0");
            
            // Generate OTAC using new service
            var otacCode = await _oddRegistrationService.GenerateOtacAsync(userId);
            var registration = await _oddRegistrationService.GetRegistrationByOtacAsync(otacCode);

            _logger.LogInformation("OTAC code {Code} generated by user {UserId} for registration {RegistrationId}", 
                otacCode, userId, registration?.Id);

            return Json(new { 
                success = true, 
                message = "OTAC code generated successfully!",
                code = otacCode,
                registrationId = registration?.Id,
                expiresAt = registration?.OtacExpiresAt?.ToString("yyyy-MM-dd HH:mm:ss UTC"),
                purpose = model.Purpose,
                issuedTo = model.IssuedTo
            });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating OTAC code for purpose {Purpose}", model.Purpose);
            return Json(new { 
                success = false, 
                message = "An error occurred while generating the OTAC code. Please try again." 
            });
        }
    }

    /// <summary>
    /// Show OTAC validation modal
    /// </summary>
    [HttpGet]
    public IActionResult ValidateModal()
    {
        return PartialView("_ValidateModal", new ValidateOtacViewModel());
    }

    /// <summary>
    /// Process OTAC validation via AJAX
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ValidateAjax(ValidateOtacViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return Json(new { 
                success = false, 
                message = "Please check your input and try again.",
                errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList()
            });
        }

        try
        {
            var clientIp = HttpContext.Connection.RemoteIpAddress?.ToString() ?? "Unknown";
            var (isValid, errorMessage) = await _oddRegistrationService.ValidateOtacAsync(model.Code, clientIp);

            if (isValid)
            {
                _logger.LogInformation("OTAC code {Code} validated successfully from IP {IP}", 
                    model.Code, clientIp);

                // Add OTAC verified claim to current session
                HttpContext.Session.SetString("otac_verified", "true");
                HttpContext.Session.SetString("otac_code", model.Code);
                HttpContext.Session.SetString("otac_verified_at", DateTime.UtcNow.ToString());

                var registration = await _oddRegistrationService.GetRegistrationByOtacAsync(model.Code);

                return Json(new { 
                    success = true, 
                    message = "OTAC code validated successfully! You now have access to protected resources.",
                    code = model.Code,
                    registrationId = registration?.Id
                });
            }
            else
            {
                _logger.LogWarning("OTAC code validation failed for code {Code} from IP {IP}: {ErrorMessage}", 
                    model.Code, clientIp, errorMessage);
                
                return Json(new { 
                    success = false, 
                    message = errorMessage
                });
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error validating OTAC code {Code}", model.Code);
            return Json(new { 
                success = false, 
                message = "An error occurred while validating the OTAC code. Please try again." 
            });
        }
    }

    /// <summary>
    /// Generate OTAC for KBank ODD guest registration - creates linked registration record
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> GenerateForKBankOdd()
    {
        try
        {
            var userId = int.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value ?? "0");

            // Generate OTAC for KBank ODD registration
            var otacCode = await _oddRegistrationService.GenerateOtacAsync(userId);
            var registration = await _oddRegistrationService.GetRegistrationByOtacAsync(otacCode);

            _logger.LogInformation("KBank ODD OTAC generated by user {UserId}: Code={Code}, RegistrationId={RegistrationId}", 
                userId, otacCode, registration?.Id);

            return Json(new { 
                success = true, 
                message = "OTAC code generated successfully for KBank ODD registration!",
                code = otacCode,
                registrationId = registration?.Id,
                expiresAt = registration?.OtacExpiresAt?.ToString("yyyy-MM-dd HH:mm:ss UTC") ?? DateTime.UtcNow.AddMinutes(30).ToString("yyyy-MM-dd HH:mm:ss UTC"),
                purpose = "KBank ODD Guest Registration"
            });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating OTAC code for KBank ODD registration");
            return Json(new { 
                success = false, 
                message = "An error occurred while generating the OTAC code for KBank ODD registration. Please try again." 
            });
        }
    }

    /// <summary>
    /// Get KBank ODD registration details by OTAC code
    /// </summary>
    [HttpGet]
    public async Task<IActionResult> GetKBankOddRegistrationDetails(string otacCode)
    {
        try
        {
            var registration = await _oddRegistrationService.GetRegistrationByOtacAsync(otacCode);
            
            if (registration == null)
            {
                return Json(new { success = false, message = "OTAC code not found or not linked to registration" });
            }
            
            return Json(new { 
                success = true,
                registration = new {
                    id = registration.Id,
                    externalReference = registration.ExternalReference,
                    status = registration.Status,
                    fullName = registration.FullName,
                    mobileNo = registration.MobileNo,
                    idType = registration.IdType,
                    idValue = registration.IdValue,
                    accountNo = registration.AccountNo,
                    branchId = registration.BranchId,
                    branchName = registration.Branch?.Name,
                    createdAt = registration.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss UTC"),
                    updatedAt = registration.UpdatedAt?.ToString("yyyy-MM-dd HH:mm:ss UTC"),
                    otacExpiresAt = registration.OtacExpiresAt?.ToString("yyyy-MM-dd HH:mm:ss UTC")
                },
                otac = new {
                    code = registration.OtacCode,
                    state = registration.OtacState,
                    createdAt = registration.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss UTC"),
                    expiresAt = registration.OtacExpiresAt?.ToString("yyyy-MM-dd HH:mm:ss UTC"),
                    isLocked = registration.IsLocked,
                    attemptCount = registration.AttemptCount,
                    lastAttemptAt = registration.LastAttemptAt?.ToString("yyyy-MM-dd HH:mm:ss UTC"),
                    lastAttemptIp = registration.LastAttemptIp
                }
            });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error retrieving KBank ODD registration details for OTAC: {OtacCode}", otacCode);
            return Json(new { 
                success = false, 
                message = "An error occurred while retrieving registration details." 
            });
        }
    }
}

/// <summary>
/// ViewModel for generating OTAC codes
/// </summary>
public class GenerateOtacViewModel
{
    [Required(ErrorMessage = "Purpose is required.")]
    [StringLength(100, MinimumLength = 3, ErrorMessage = "Purpose must be between 3 and 100 characters.")]
    [Display(Name = "Purpose")]
    public string Purpose { get; set; } = string.Empty;

    [Required(ErrorMessage = "Issued To is required.")]
    [StringLength(256, ErrorMessage = "Issued To cannot exceed 256 characters.")]
    [Display(Name = "Issued To")]
    public string IssuedTo { get; set; } = string.Empty;
    
    [Display(Name = "Registration ID")]
    public int? RegistrationId { get; set; }
}

/// <summary>
/// ViewModel for validating OTAC codes
/// </summary>
public class ValidateOtacViewModel
{
    [Required(ErrorMessage = "OTAC code is required.")]
    [StringLength(8, MinimumLength = 8, ErrorMessage = "OTAC code must be exactly 8 characters.")]
    [RegularExpression(@"^[A-Z0-9]{8}$", ErrorMessage = "OTAC code must contain only uppercase letters and numbers.")]
    [Display(Name = "OTAC Code")]
    public string Code { get; set; } = string.Empty;
}