using System.ComponentModel.DataAnnotations;
using BizConnect.Dal.Models;
using BizConnect.Services.Interfaces;
using BizConnect.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BizConnect.Areas.Admin.Controllers;

/// <summary>
/// Controller for managing One-Time Access Codes (OTAC) integrated with ODD registrations
/// Accessible by Admin and Employee roles only
/// </summary>
public class OtacController : BaseAdminController
{
    private readonly IOtacManagementService _otacService;
    private readonly IRegistrationQueryService _registrationQuery;
    private readonly ILogger<OtacController> _logger;

    public OtacController(IOtacManagementService otacService, IRegistrationQueryService registrationQuery, ILogger<OtacController> logger)
    {
        _otacService = otacService;
        _registrationQuery = registrationQuery;
        _logger = logger;
    }

    /// <summary>
    /// Display list of OTAC registrations
    /// </summary>
    public async Task<IActionResult> Index()
    {
        var language = GetCurrentLanguage();
        var result = await _registrationQuery.GetPagedAsync(page: 1, pageSize: 50, language: language);
        if (result.IsSuccess)
        {
            return View(result.Data?.Items ?? new List<KbankOddRegistration>());
        }
        
        TempData["ErrorMessage"] = "Unable to load registrations: " + result.ErrorMessage;
        return View(new List<KbankOddRegistration>());
    }

    /// <summary>
    /// Generate a new OTAC code
    /// </summary>
    [HttpGet]
    public IActionResult Generate()
    {
        return View(new GenerateOtacViewModel());
    }

    /// <summary>
    /// Process OTAC code generation
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Generate(GenerateOtacViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var userId = User.GetUserId();
        if (userId == 0)
        {
            ModelState.AddModelError(string.Empty, "Unable to identify user. Please log in again.");
            return View(model);
        }

        var language = GetCurrentLanguage();
        var result = await _otacService.GenerateAsync(userId, model.Purpose, language);
        
        if (result.IsSuccess)
        {
            _logger.LogInformation("OTAC code {Code} generated by user {UserId} for purpose {Purpose}", 
                result.Code, userId, model.Purpose);

            TempData["SuccessMessage"] = $"OTAC code generated successfully: {result.Code}";
            TempData["GeneratedCode"] = result.Code;
            TempData["RegistrationId"] = result.RegistrationId;
            TempData["ExpiresAt"] = result.ExpiresAt?.ToString("yyyy-MM-dd HH:mm:ss UTC");

            return RedirectToAction(nameof(Index));
        }
        else
        {
            _logger.LogError("Error generating OTAC code for purpose {Purpose}: {ErrorMessage}", model.Purpose, result.ErrorMessage);
            ModelState.AddModelError(string.Empty, result.ErrorMessage ?? "An error occurred while generating the OTAC code. Please try again.");
            return View(model);
        }
    }

    /// <summary>
    /// Validate an OTAC code
    /// </summary>
    [HttpGet]
    public IActionResult Validate()
    {
        return View(new ValidateOtacViewModel());
    }

    /// <summary>
    /// Process OTAC code validation
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Validate(ValidateOtacViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var clientIp = HttpContext.GetClientIpAddress();
        var language = GetCurrentLanguage();
        var result = await _otacService.ValidateAsync(model.Code, clientIp, language);

        if (result.IsSuccess)
        {
            _logger.LogInformation("OTAC code {Code} validated successfully from IP {IP}", 
                model.Code, clientIp);

            // Add OTAC verified claim to current session
            HttpContext.SetOtacVerified(model.Code);

            TempData["SuccessMessage"] = "OTAC code validated successfully. You now have access to protected resources.";
            return RedirectToAction("Index", "Home");
        }
        else
        {
            _logger.LogWarning("OTAC code validation failed for code {Code} from IP {IP}: {ErrorMessage}", 
                model.Code, clientIp, result.ErrorMessage);
            ModelState.AddModelError(string.Empty, result.ErrorMessage ?? "Invalid OTAC code.");
        }

        return View(model);
    }

    /// <summary>
    /// View OTAC registrations generated by current user
    /// </summary>
    public async Task<IActionResult> MyOtacCodes()
    {
        var userId = User.GetUserId();
        var language = GetCurrentLanguage();
        var result = await _registrationQuery.GetPagedAsync(page: 1, pageSize: 100, language: language);
        
        if (result.IsSuccess && result.Data != null)
        {
            // Filter by current user (this could be optimized with a search parameter in the service)
            var userRegistrations = result.Data.Items.Where(r => r.GeneratedByUserId == userId);
            return View(userRegistrations);
        }
        
        TempData["ErrorMessage"] = "Unable to load your OTAC codes: " + result.ErrorMessage;
        return View(new List<KbankOddRegistration>());
    }

    /// <summary>
    /// Manual purge of expired OTAC codes (Admin only)
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Policy = "AdminOnly")]
    public async Task<IActionResult> PurgeExpired()
    {
        var result = await _otacService.PurgeExpiredAsync();
        
        if (result.IsSuccess)
        {
            TempData["SuccessMessage"] = "Successfully purged expired OTAC registrations.";
        }
        else
        {
            _logger.LogError("Error purging expired OTAC registrations: {ErrorMessage}", result.ErrorMessage);
            TempData["ErrorMessage"] = result.ErrorMessage ?? "An error occurred while purging expired registrations.";
        }

        return RedirectToAction(nameof(Index));
    }

    /// <summary>
    /// Generate OTAC modal for specific registration
    /// </summary>
    [HttpGet]
    public IActionResult GenerateModal(int? registrationId = null)
    {
        var model = new GenerateOtacViewModel();
        
        if (registrationId.HasValue)
        {
            model.Purpose = $"ODD Registration #{registrationId}";
            model.RegistrationId = registrationId.Value;
        }
        
        return PartialView("_GenerateModal", model);
    }

    /// <summary>
    /// Process OTAC generation via AJAX
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> GenerateAjax(GenerateOtacViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return Json(new { 
                success = false, 
                message = "Please check your input and try again.",
                errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList()
            });
        }

        var userId = User.GetUserId();
        if (userId == 0)
        {
            return Json(new { 
                success = false, 
                message = "Unable to identify user. Please log in again." 
            });
        }

        var language = GetCurrentLanguage();
        var result = await _otacService.GenerateAsync(userId, model.Purpose, language);
        
        if (result.IsSuccess)
        {
            _logger.LogInformation("OTAC code {Code} generated by user {UserId} for purpose {Purpose}", 
                result.Code, userId, model.Purpose);

            return Json(new { 
                success = true, 
                message = "OTAC code generated successfully!",
                code = result.Code,
                registrationId = result.RegistrationId,
                expiresAt = result.ExpiresAt?.ToString("yyyy-MM-dd HH:mm:ss UTC"),
                purpose = model.Purpose,
                issuedTo = model.IssuedTo
            });
        }
        else
        {
            _logger.LogError("Error generating OTAC code for purpose {Purpose}: {ErrorMessage}", model.Purpose, result.ErrorMessage);
            return Json(new { 
                success = false, 
                message = result.ErrorMessage ?? "An error occurred while generating the OTAC code. Please try again." 
            });
        }
    }

    /// <summary>
    /// Show OTAC validation modal
    /// </summary>
    [HttpGet]
    public IActionResult ValidateModal()
    {
        return PartialView("_ValidateModal", new ValidateOtacViewModel());
    }

    /// <summary>
    /// Process OTAC validation via AJAX
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ValidateAjax(ValidateOtacViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return Json(new { 
                success = false, 
                message = "Please check your input and try again.",
                errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList()
            });
        }

        var clientIp = HttpContext.GetClientIpAddress();
        var language = GetCurrentLanguage();
        var result = await _otacService.ValidateAsync(model.Code, clientIp, language);

        if (result.IsSuccess)
        {
            _logger.LogInformation("OTAC code {Code} validated successfully from IP {IP}", 
                model.Code, clientIp);

            // Add OTAC verified claim to current session
            HttpContext.SetOtacVerified(model.Code);

            return Json(new { 
                success = true, 
                message = "OTAC code validated successfully! You now have access to protected resources.",
                code = model.Code,
                registrationId = result.RegistrationId
            });
        }
        else
        {
            _logger.LogWarning("OTAC code validation failed for code {Code} from IP {IP}: {ErrorMessage}", 
                model.Code, clientIp, result.ErrorMessage);
            
            return Json(new { 
                success = false, 
                message = result.ErrorMessage ?? "Invalid OTAC code."
            });
        }
    }

    /// <summary>
    /// Generate OTAC for KBank ODD guest registration - creates linked registration record
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> GenerateForKBankOdd()
    {
        var userId = User.GetUserId();
        if (userId == 0)
        {
            return Json(new { 
                success = false, 
                message = "Unable to identify user. Please log in again." 
            });
        }

        var language = GetCurrentLanguage();
        var result = await _otacService.GenerateAsync(userId, "KBank ODD Guest Registration", language);
        
        if (result.IsSuccess)
        {
            _logger.LogInformation("KBank ODD OTAC generated by user {UserId}: Code={Code}, RegistrationId={RegistrationId}", 
                userId, result.Code, result.RegistrationId);

            return Json(new { 
                success = true, 
                message = "OTAC code generated successfully for KBank ODD registration!",
                code = result.Code,
                registrationId = result.RegistrationId,
                expiresAt = result.ExpiresAt?.ToString("yyyy-MM-dd HH:mm:ss UTC"),
                purpose = "KBank ODD Guest Registration"
            });
        }
        else
        {
            _logger.LogError("Error generating OTAC code for KBank ODD registration: {ErrorMessage}", result.ErrorMessage);
            return Json(new { 
                success = false, 
                message = result.ErrorMessage ?? "An error occurred while generating the OTAC code for KBank ODD registration. Please try again." 
            });
        }
    }

    /// <summary>
    /// Get KBank ODD registration details by OTAC code
    /// </summary>
    [HttpGet]
    public async Task<IActionResult> GetKBankOddRegistrationDetails(string otacCode)
    {
        var language = GetCurrentLanguage();
        var otacInfo = await _otacService.GetInfoAsync(otacCode, language);
        
        if (!otacInfo.IsSuccess || otacInfo.RegistrationId == null)
        {
            return Json(new { success = false, message = otacInfo.ErrorMessage ?? "OTAC code not found or not linked to registration" });
        }

        // Note: This method would need to be updated once we have the actual registration by GUID lookup
        // For now, return OTAC info only
        return Json(new { 
            success = true,
            otac = new {
                code = otacInfo.Code,
                registrationId = otacInfo.RegistrationId,
                purpose = otacInfo.Data?.Purpose,
                expiresAt = otacInfo.ExpiresAt?.ToString("yyyy-MM-dd HH:mm:ss UTC"),
                remainingAttempts = otacInfo.RemainingAttempts
            }
        });
    }
}

/// <summary>
/// ViewModel for generating OTAC codes
/// </summary>
public class GenerateOtacViewModel
{
    [Required(ErrorMessage = "Purpose is required.")]
    [StringLength(100, MinimumLength = 3, ErrorMessage = "Purpose must be between 3 and 100 characters.")]
    [Display(Name = "Purpose")]
    public string Purpose { get; set; } = string.Empty;

    [Required(ErrorMessage = "Issued To is required.")]
    [StringLength(256, ErrorMessage = "Issued To cannot exceed 256 characters.")]
    [Display(Name = "Issued To")]
    public string IssuedTo { get; set; } = string.Empty;
    
    [Display(Name = "Registration ID")]
    public int? RegistrationId { get; set; }
}

/// <summary>
/// ViewModel for validating OTAC codes
/// </summary>
public class ValidateOtacViewModel
{
    [Required(ErrorMessage = "OTAC code is required.")]
    [StringLength(8, MinimumLength = 8, ErrorMessage = "OTAC code must be exactly 8 characters.")]
    [RegularExpression(@"^[A-Z0-9]{8}$", ErrorMessage = "OTAC code must contain only uppercase letters and numbers.")]
    [Display(Name = "OTAC Code")]
    public string Code { get; set; } = string.Empty;
}